[github_user]
type = "string"
description = "GitHub User"

[[ignore]]
condition = "{{ crate_lib }}"
paths = ["src/main.rs"]

[[ignore]]
condition = "{{ crate_bin }}"
paths = ["src/lib.rs", ".github/workflows/docs.yml"]
